channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=24.2
- pip:
  - mlflow==2.14.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - packaging==24.1
  - pyyaml==6.0.2
  - scikit-learn==1.5.1
  - scipy==1.13.1
name: mlflow-env
