channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.2.1
- pip:
  - mlflow==2.14.3
  - cloudpickle==2.2.1
  - feature-engine==1.8.0
  - numpy==1.24.3
  - packaging==23.1
  - pandas==2.2.2
  - psutil==5.9.5
  - pyyaml==6.0
  - scikit-learn==1.5.1
  - scipy==1.11.2
name: mlflow-env
