channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.2.1
- pip:
  - mlflow==2.14.3
  - cloudpickle==2.2.1
  - feature-engine==1.8.0
  - lz4==4.3.2
  - numpy==1.26.3
  - packaging==23.1
  - pandas==2.2.2
  - pathlib==1.0.1
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.5.1
  - scipy==1.11.4
name: mlflow-env
